### ISSUE TITLE
source web disappear 

### ISSUE THREAD

**Issue by winglu0821** [laub1199/cityu-cs-tg-bot-os#1]
cannot open the source file "https://github.com/laub1199/cityu-cs-tg-bot/raw/master/source/", how to fix it

**Comment by sennett-lau** [comment]
Thanks for raising this issue, a hotfix has been on [v0.1.1](https://github.com/laub1199/cityu-cs-tg-bot-os/releases/tag/v0.1.1)
The `/source` command should work properly now!
